"""Security layer for Seeknal Ask agent-generated SQL.

More restrictive than the REPL's validate_sql() — blocks DuckDB functions
that can read arbitrary files or make network requests, even within
otherwise-valid SELECT statements.
"""

import re

# DuckDB functions that bypass read-only intent by accessing
# the filesystem or network. Must be blocked in agent-generated SQL.
AGENT_BLOCKED_FUNCTIONS = {
    "read_text",
    "read_blob",
    "read_csv",
    "read_csv_auto",
    "read_json",
    "read_json_auto",
    "read_json_objects",
    "read_parquet",
    "read_ndjson",
    "read_ndjson_auto",
    "read_ndjson_objects",
    "glob",
    "http_get",
    "http_post",
    "httpfs_get",
    "httpfs_post",
    # Scan aliases that bypass read_parquet block
    "parquet_scan",
    "scan_parquet",
    "iceberg_scan",
    "iceberg_metadata",
    "delta_scan",
    # Write functions
    "write_parquet",
    "write_csv",
    # Environment / settings leakage
    "getenv",
    "current_setting",
}

# Additional keywords blocked for agent connections beyond REPL's list.
# These can modify DuckDB state or load extensions.
AGENT_BLOCKED_KEYWORDS = [
    "INSTALL",
    "LOAD",
    "ATTACH",
    "DETACH",
    "SET",
    "PRAGMA",
    "COPY",
    "EXPORT",
    "IMPORT",
]


def validate_sql_for_agent(sql: str) -> None:
    """Validate agent-generated SQL with strict security rules.

    Checks:
    1. REPL's existing read-only allowlist (SELECT/WITH/DESCRIBE/SHOW)
    2. Blocked DuckDB functions (file/network access)
    3. Blocked keywords (state modification)

    Args:
        sql: SQL query string generated by the LLM agent.

    Raises:
        ValueError: If the SQL fails any validation check.
    """
    from seeknal.cli.repl import validate_sql

    # Phase 1: existing REPL validation (read-only allowlist + dangerous keywords)
    is_valid, error_msg = validate_sql(sql)
    if not is_valid:
        raise ValueError(error_msg)

    # Phase 2: block dangerous DuckDB functions
    sql_lower = sql.lower()
    for func in AGENT_BLOCKED_FUNCTIONS:
        # Match function name followed by opening paren, with optional whitespace
        pattern = r"\b" + re.escape(func) + r"\s*\("
        if re.search(pattern, sql_lower):
            raise ValueError(
                f"Function '{func}' is not allowed in agent-generated queries. "
                f"Only queries against registered views and tables are permitted."
            )

    # Phase 3: block state-modifying keywords
    sql_upper = sql.strip().upper()
    for keyword in AGENT_BLOCKED_KEYWORDS:
        pattern = r"\b" + keyword + r"\b"
        if re.search(pattern, sql_upper):
            raise ValueError(
                f"Keyword '{keyword}' is not allowed in agent-generated queries."
            )


def configure_safe_connection(conn) -> None:
    """Apply security settings to a DuckDB connection used by the agent.

    Note: We do NOT set enable_external_access = false because DuckDB views
    are lazy — they re-evaluate read_parquet() on each query. Disabling
    external access would break all registered views. Instead, security is
    enforced by the function blocklist in validate_sql_for_agent().

    Resource limits prevent DoS via expensive queries.

    Args:
        conn: A DuckDB connection object.
    """
    conn.execute("SET max_memory = '512MB'")
    conn.execute("SET threads = 2")
