"""Bootstrap semantic model tool — profiles data and generates draft semantic model YAML."""

from langchain_core.tools import tool


@tool
def bootstrap_semantic_model(table_name: str = "") -> str:
    """Profile data files and generate draft semantic model YAML.

    Scans data/ CSVs and target/intermediate/ parquets, classifies columns
    (entities, dimensions, measures), and writes draft YAML files.

    Args:
        table_name: Optional. If provided, bootstrap only this table.
                    If empty, bootstrap all discovered tables.

    Returns:
        Summary of generated models, or guidance if no data found.
    """
    from seeknal.ask.agents.tools._context import get_tool_context
    from seeknal.workflow.semantic.bootstrap import (
        _build_semantic_model_dict,
        _discover_tables,
        _profile_table,
    )

    ctx = get_tool_context()

    tables = _discover_tables(ctx.project_path)

    if table_name:
        tables = [(n, p, r) for n, p, r in tables if n == table_name]
        if not tables:
            return (
                f"No data file found for table '{table_name}'.\n"
                "Looked in data/*.csv and target/intermediate/*.parquet."
            )

    if not tables:
        return (
            "No data files found to bootstrap.\n"
            "Place CSV files in data/ or run a pipeline to generate "
            "parquet files in target/intermediate/."
        )

    import duckdb
    import yaml

    con = duckdb.connect(":memory:")
    generated: list[dict] = []
    draft_files: list[str] = []

    try:
        for tbl_name, file_path, model_ref in tables:
            try:
                column_infos, row_count = _profile_table(con, tbl_name, file_path)
                model_dict = _build_semantic_model_dict(tbl_name, model_ref, column_infos)

                # Write as draft file in project root (draft/apply pattern)
                yaml_content = yaml.safe_dump(
                    model_dict, default_flow_style=False, sort_keys=False
                )
                content = (
                    "# AUTO-GENERATED by seeknal semantic bootstrap\n"
                    "# Review and adjust entities, dimensions, and measures "
                    "as needed.\n"
                    f"{yaml_content}"
                )

                draft_name = f"draft_semantic_model_{tbl_name}.yml"
                draft_path = ctx.project_path / draft_name

                with ctx.fs_lock:
                    draft_path.write_text(content)

                generated.append(model_dict)
                draft_files.append(draft_name)
            except Exception as e:
                draft_files.append(f"(skipped {tbl_name}: {e})")
    finally:
        con.close()

    if not generated:
        return "Failed to profile any tables. Check that data files are readable."

    # Build summary
    lines = [f"Generated {len(generated)} semantic model draft(s):\n"]
    for model_dict, draft_name in zip(generated, draft_files):
        entities = [e["name"] for e in model_dict.get("entities", [])]
        measures = [m["name"] for m in model_dict.get("measures", [])]
        dims = [d["name"] for d in model_dict.get("dimensions", [])]
        lines.append(f"**{draft_name}**")
        if entities:
            lines.append(f"  Entities: {', '.join(entities)}")
        if dims:
            lines.append(f"  Dimensions: {', '.join(dims)}")
        if measures:
            lines.append(f"  Measures: {', '.join(measures)}")
        lines.append("")

    lines.append("Next steps:")
    lines.append("1. Review the draft files")
    lines.append("2. Apply with apply_draft('draft_semantic_model_<name>.yml', confirmed=True)")
    lines.append("3. Query metrics with query_metric()")

    return "\n".join(lines)
