#!/bin/bash

# Auto-Build Environment Setup for API Documentation
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Documentation Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# CHECK REQUIREMENTS
# ============================================

echo ""
echo "Checking requirements..."

# Check if Python 3.11+ is available
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version | awk '{print $2}' | cut -d'.' -f1,2)
    echo "Python version: $PYTHON_VERSION"
    if [ "$(echo "$PYTHON_VERSION >= 3.11" | bc)" -eq 0 ]; then
        echo -e "${RED}Python 3.11+ required${NC}"
        exit 1
    fi
else
    echo -e "${RED}Python 3 not found${NC}"
    exit 1
fi

# Check if pip is available
if ! command -v pip &> /dev/null; then
    echo -e "${RED}pip not found${NC}"
    exit 1
fi

# ============================================
# INSTALL DOCUMENTATION DEPENDENCIES
# ============================================

echo ""
echo "Installing documentation dependencies..."

if [ -f "requirements-docs.txt" ]; then
    echo "Installing from requirements-docs.txt..."
    pip install -r requirements-docs.txt
else
    echo -e "${YELLOW}requirements-docs.txt not found - install manually:${NC}"
    echo "  pip install mkdocs mkdocs-material 'mkdocstrings[python]'"
fi

# ============================================
# VERIFY INSTALLATION
# ============================================

echo ""
echo "Verifying MkDocs installation..."

if ! command -v mkdocs &> /dev/null; then
    echo -e "${RED}MkDocs not installed properly${NC}"
    exit 1
fi

echo -e "${GREEN}MkDocs installed: $(mkdocs --version)${NC}"

# ============================================
# CHECK CONFIGURATION
# ============================================

echo ""
echo "Checking documentation configuration..."

if [ ! -f "mkdocs.yml" ]; then
    echo -e "${YELLOW}mkdocs.yml not found - documentation setup incomplete${NC}"
    echo "Run subtasks from phase-1-setup to create configuration"
else
    echo -e "${GREEN}mkdocs.yml found${NC}"
fi

if [ ! -d "docs" ]; then
    echo -e "${YELLOW}docs/ directory not found - documentation setup incomplete${NC}"
else
    echo -e "${GREEN}docs/ directory found${NC}"
fi

# ============================================
# START DOCUMENTATION SERVER
# ============================================

echo ""
echo "========================================"
echo "Starting MkDocs Development Server"
echo "========================================"
echo ""
echo "Documentation will be available at: http://localhost:8000"
echo "Press Ctrl+C to stop the server"
echo ""

# Start mkdocs serve with hot reload
mkdocs serve

# Note: This script keeps running until mkdocs serve is stopped
