name: Pytest Pipeline

on:
  pull_request:
    branches:
      - "**" # Run on all branches when a PR is opened
  push:
    branches:
      - main # Run when code is merged into the master branch

jobs:
  run-pytest:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          python3.11 -m pip install --upgrade pip
          pip3.11 install -e .

      # Run tests
      - name: Run pytest
        run: |
          pytest -s src/tests
