name: Pytest Pipeline

on:
  pull_request:
    branches:
      - "**" # Run on all branches when a PR is opened
  push:
    branches:
      - main # Run when code is merged into the master branch

jobs:
  run-pytest:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.11" # Change to your project's Python version if needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      # Run tests
      - name: Run pytest
        run: |
          pytest -s src/tests
